[package]
name = "zksync-tia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
celestia-rpc = "0.2.0"
celestia-types = "0.2.0"
thiserror = "1.0.59"
